# Generated by Django 2.2.6 on 2020-08-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='failure_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='failure_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
