# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-02 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('adress', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(blank=True, choices=[(b'Aguascalientes', b'AGUASCALIENTES'), (b'Baja California', b'BAJA CALIFORNIA'), (b'Baja California Sur', b'BAJA CALIFORNIA SUR'), (b'Campeche', b'CAMPECHE'), (b'Chiapas', b'CHIAPAS'), (b'Mexico City', b'MEXICO CITY'), (b'Chihuahua', b'CHIHUAHUA'), (b'Coahuila', b'COAHUILA'), (b'Colima', b'COLIMA'), (b'Durango', b'DURANGO'), (b'Guanajuato', b'GUANAJUATO'), (b'Guerrero', b'GUERRERO'), (b'Hidalgo', b'HIDALGO'), (b'Jalisco', b'JALISCO'), (b'Mexico', b'MEXICO'), (b'Michoacan', b'MICHOACAN'), (b'Morelos', b'MORELOS'), (b'Nayarit', b'NAYARIT'), (b'Nuevo Leon', b'NUEVO LEON'), (b'Oaxaca', b'OAXACA'), (b'Puebla', b'PUEBLA'), (b'Queretaro', b'QUERETARO'), (b'Quintana Roo', b'QUINTANA ROO'), (b'San Luis Potosi', b'SAN LUIS POTOSI'), (b'Sinaloa', b'SINALOA'), (b'Sonora', b'SONORA'), (b'Tabasco', b'TABASCO'), (b'Tamaulipas', b'TAMAULIPAS'), (b'Tlaxcala', b'TLAXCALA'), (b'Veracruz', b'VERACRUZ'), (b'Yucatan', b'YUCATAN'), (b'Zacatecas', b'ZACATECAS')], default=b'null', max_length=40)),
                ('telefon', models.IntegerField(blank=True, default=b'null', null=True)),
                ('acceptpacients', models.BooleanField(default=True)),
                ('web', models.CharField(default=b'null', max_length=60)),
                ('email', models.EmailField(blank=True, default=b'null', max_length=254)),
                ('verificated', models.BooleanField(default=False)),
                ('IdentificationUser', models.FileField(upload_to=b'')),
                ('occupancy', models.CharField(blank=True, choices=[(b'Pacient', b'PACIENT'), (b'Doctor', b'DOCTOR'), (b'STUDENT', b'STUDENT')], default=b'null', max_length=40)),
                ('speciality', models.CharField(blank=True, default=b'null', max_length=60)),
                ('ratinghelp', models.IntegerField(default=b'5')),
                ('ratingkind', models.IntegerField(default=b'5')),
                ('ratingtime', models.IntegerField(default=b'5')),
                ('ratingstaff', models.IntegerField(default=b'5')),
                ('ratingethic', models.IntegerField(default=b'5')),
                ('followers', models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
            ],
        ),
    ]
