# Generated by Django 2.2.6 on 2019-10-08 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurancecompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='null', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='colony',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='englishspeaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome1',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome1Text1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome1Text2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome2',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome2Text1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome2Text2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome3',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome3Text1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='imagehome3Text2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lat',
            field=models.FloatField(blank=True, default=30, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='lng',
            field=models.FloatField(blank=True, default=30, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='slug',
            field=models.SlugField(default='ivo', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='workingtime',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='IdentificationUser',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(blank=True, default='null', max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='occupancy',
            field=models.CharField(blank=True, choices=[('Pacient', 'PACIENT'), ('Doctor', 'DOCTOR'), ('STUDENT', 'STUDENT')], default='Pacient', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ratingethic',
            field=models.IntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ratinghelp',
            field=models.IntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ratingkind',
            field=models.IntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ratingstaff',
            field=models.IntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ratingtime',
            field=models.IntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='speciality',
            field=models.CharField(blank=True, default='null', max_length=60),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(blank=True, choices=[('Aguascalientes', 'AGUASCALIENTES'), ('Baja California', 'BAJA CALIFORNIA'), ('Baja California Sur', 'BAJA CALIFORNIA SUR'), ('Campeche', 'CAMPECHE'), ('Chiapas', 'CHIAPAS'), ('Mexico City', 'MEXICO CITY'), ('Chihuahua', 'CHIHUAHUA'), ('Coahuila', 'COAHUILA'), ('Colima', 'COLIMA'), ('Durango', 'DURANGO'), ('Guanajuato', 'GUANAJUATO'), ('Guerrero', 'GUERRERO'), ('Hidalgo', 'HIDALGO'), ('Jalisco', 'JALISCO'), ('Mexico', 'MEXICO'), ('Michoacan', 'MICHOACAN'), ('Morelos', 'MORELOS'), ('Nayarit', 'NAYARIT'), ('Nuevo Leon', 'NUEVO LEON'), ('Oaxaca', 'OAXACA'), ('Puebla', 'PUEBLA'), ('Queretaro', 'QUERETARO'), ('Quintana Roo', 'QUINTANA ROO'), ('San Luis Potosi', 'SAN LUIS POTOSI'), ('Sinaloa', 'SINALOA'), ('Sonora', 'SONORA'), ('Tabasco', 'TABASCO'), ('Tamaulipas', 'TAMAULIPAS'), ('Tlaxcala', 'TLAXCALA'), ('Veracruz', 'VERACRUZ'), ('Yucatan', 'YUCATAN'), ('Zacatecas', 'ZACATECAS')], default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='telefon',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='web',
            field=models.CharField(default='null', max_length=60),
        ),
        migrations.CreateModel(
            name='UserDetailsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagehome3', models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location_gal)),
                ('weburl', models.URLField(blank=True)),
                ('teamname', models.CharField(blank=True, max_length=60, null=True)),
                ('teamtext', models.TextField(blank=True, max_length=120)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsSpecialistIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialityName', models.CharField(blank=True, max_length=60, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavicon', models.CharField(blank=True, max_length=60, null=True)),
                ('servicename', models.CharField(blank=True, max_length=60, null=True)),
                ('servicetext', models.TextField(blank=True, max_length=120)),
                ('weburl', models.URLField(blank=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default='5.0')),
                ('ratinghelp', models.IntegerField(default='5')),
                ('ratingkind', models.IntegerField(default='5')),
                ('ratingtime', models.IntegerField(default='5')),
                ('ratingstaff', models.IntegerField(default='5')),
                ('ratingethic', models.IntegerField(default='5')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagehome3', models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location_gal)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagehome3', models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location_gal)),
                ('weburl', models.URLField(blank=True)),
                ('departmentname', models.CharField(blank=True, max_length=60, null=True)),
                ('departmenttext', models.TextField(blank=True, max_length=120)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='insurancecompany',
            field=models.ManyToManyField(to='newsletter.Insurancecompany'),
        ),
    ]
