# Generated by Django 2.2.6 on 2019-10-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20191009_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='insurancecompany',
        ),
    ]
