# Generated by Django 2.2.6 on 2019-10-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_userdetails_insurancecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='insurancecompany',
            field=models.ManyToManyField(to='newsletter.Insurancecompany'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lat',
            field=models.FloatField(blank=True, default=1.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='lng',
            field=models.FloatField(blank=True, default=1.0, max_length=100),
        ),
    ]
