# Generated by Django 2.2.6 on 2019-10-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20191009_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsServicePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprice', models.IntegerField(blank=True, max_length=10, null=True)),
                ('servicepricediscount', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='acceptanimales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='acceptchildren',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='homevisit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='invalidsaccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='specialprice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='web',
            field=models.URLField(default='null'),
        ),
        migrations.DeleteModel(
            name='UserDetailsSpecialistIn',
        ),
        migrations.AddField(
            model_name='userdetailsserviceprice',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails'),
        ),
        migrations.AddField(
            model_name='userdetailsserviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetailsService'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='paymentmethod',
            field=models.ManyToManyField(to='newsletter.Paymentmethod'),
        ),
    ]
