# Generated by Django 2.2.6 on 2020-09-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20200901_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='null', max_length=254)),
            ],
        ),
    ]
