# Generated by Django 2.2.6 on 2020-09-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_newslettermail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='meta_keywords',
            field=models.TextField(blank=True, default='', verbose_name='Post meta keywords'),
        ),
    ]
