# Generated by Django 2.2.6 on 2019-10-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20191012_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='description',
            field=models.CharField(blank=True, default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(blank=True, default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='userdetailsservice',
            name='servicename',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='UserDetailsServicePackagePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(null=True)),
                ('packagepricediscount', models.IntegerField(blank=True, max_length=10, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
                ('selectservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetailsService')),
            ],
        ),
        
    ]
