# Generated by Django 2.2.6 on 2020-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_userdetails_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='web',
            field=models.URLField(blank=True, default='null'),
        ),
    ]
