# Generated by Django 2.2.6 on 2019-10-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20191016_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsservicepackageprice',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
        
    ]
