# Generated by Django 2.2.6 on 2020-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20201001_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='about_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservice',
            name='servicename_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservice',
            name='servicename_es',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservice',
            name='servicetext_en',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservice',
            name='servicetext_es',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='extragift_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='extragift_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='headdescription_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='headdescription_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsteam',
            name='teamtext_en',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsteam',
            name='teamtext_es',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
