# Generated by Django 2.2.6 on 2019-10-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20191017_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        
    ]
