# Generated by Django 2.2.6 on 2019-10-23 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20191019_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsserviceprice',
            name='servicepricediscount',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        
    ]
