# Generated by Django 2.2.6 on 2020-10-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20201005_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailsservicepackageprice',
            name='selectservice',
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='selectservice',
            field=models.ManyToManyField(to='newsletter.UserDetailsService'),
        ),
    ]
