# Generated by Django 2.2.6 on 2020-10-13 08:31

import constrainedfilefield.fields.file
from django.db import migrations
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20201006_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='the_file',
            field=constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=['image/png'], max_upload_size=10240, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location),
        ),
    ]
