# Generated by Django 2.2.6 on 2019-10-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20191023_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='workingtime',
            new_name='startworkingtimeMonFriday',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='endworkingtimeMonFriday',
            field=models.TimeField(default='15:00'),
        ),
    ]
