# Generated by Django 2.2.6 on 2019-11-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20191024_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='endworkingtimeSat',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='startworkingtimeSat',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='endworkingtimeMonFriday',
            field=models.TimeField(default='17:00'),
        ),
    ]
