# Generated by Django 2.2.6 on 2019-11-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20191111_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='emergencycalls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='endworkingtimeSun',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='startworkingtimeSun',
            field=models.TimeField(default='08:00'),
        ),
    ]
