# Generated by Django 2.2.6 on 2020-10-13 08:49

import constrainedfilefield.fields.file
import constrainedfilefield.fields.image
from django.db import migrations
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20201013_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='the_file',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='IdentificationUser',
            field=constrainedfilefield.fields.file.ConstrainedFileField(js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profilepicture',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, content_types=['image/jpeg', 'image/jpg', 'image/jpg'], js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location),
        ),
    ]
