# Generated by Django 2.2.6 on 2020-01-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_auto_20191111_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsServiceSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='state',
            field=models.CharField(blank=True, choices=[('', 'Select_state'), ('Aguascalientes', 'AGUASCALIENTES'), ('Baja California', 'BAJA CALIFORNIA'), ('Baja California Sur', 'BAJA CALIFORNIA SUR'), ('Campeche', 'CAMPECHE'), ('Chiapas', 'CHIAPAS'), ('Mexico City', 'MEXICO CITY'), ('Chihuahua', 'CHIHUAHUA'), ('Coahuila', 'COAHUILA'), ('Colima', 'COLIMA'), ('Durango', 'DURANGO'), ('Guanajuato', 'GUANAJUATO'), ('Guerrero', 'GUERRERO'), ('Hidalgo', 'HIDALGO'), ('Jalisco', 'JALISCO'), ('Mexico', 'MEXICO'), ('Michoacan', 'MICHOACAN'), ('Morelos', 'MORELOS'), ('Nayarit', 'NAYARIT'), ('Nuevo Leon', 'NUEVO LEON'), ('Oaxaca', 'OAXACA'), ('Puebla', 'PUEBLA'), ('Queretaro', 'QUERETARO'), ('Quintana Roo', 'QUINTANA ROO'), ('San Luis Potosi', 'SAN LUIS POTOSI'), ('Sinaloa', 'SINALOA'), ('Sonora', 'SONORA'), ('Tabasco', 'TABASCO'), ('Tamaulipas', 'TAMAULIPAS'), ('Tlaxcala', 'TLAXCALA'), ('Veracruz', 'VERACRUZ'), ('Yucatan', 'YUCATAN'), ('Zacatecas', 'ZACATECAS')], default='null', max_length=40),
        ),
    ]
