# Generated by Django 2.2.6 on 2020-10-13 09:35

import constrainedfilefield.fields.image
from django.db import migrations
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_auto_20201013_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='imagehome1',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='imagehome2',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='imagehome3',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profilepicture',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location),
        ),
        migrations.AlterField(
            model_name='userdetailsdepartment',
            name='imagehomedep',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location_gal),
        ),
        migrations.AlterField(
            model_name='userdetailsgallery',
            name='imagehomegallery',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location_gal),
        ),
        migrations.AlterField(
            model_name='userdetailsservicepackageprice',
            name='packageimage',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location_package),
        ),
        migrations.AlterField(
            model_name='userdetailsteam',
            name='imagehometeam',
            field=constrainedfilefield.fields.image.ConstrainedImageField(blank=True, js_checker=True, max_upload_size=2621440, mime_lookup_length=4096, null=True, upload_to=newsletter.models.uplodad_location_gal),
        ),
    ]
