# Generated by Django 2.2.6 on 2020-03-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_auto_20200320_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetailsdepartment',
            old_name='imagehome3',
            new_name='imagehomedep',
        ),
        migrations.RenameField(
            model_name='userdetailsgallery',
            old_name='imagehome3',
            new_name='imagehomegallery',
        ),
        migrations.RenameField(
            model_name='userdetailsteam',
            old_name='imagehome3',
            new_name='imagehometeam',
        ),
    ]
