# Generated by Django 2.2.6 on 2020-04-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0015_auto_20200329_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='endworkingtimeMonFriday',
            new_name='endworkingtimeFriday',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='endworkingtimeSat',
            new_name='endworkingtimeSaturday',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='endworkingtimeSun',
            new_name='endworkingtimeSunday',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='startworkingtimeMonFriday',
            new_name='startworkingtimeFriday',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='startworkingtimeSat',
            new_name='startworkingtimeMonday',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='startworkingtimeSun',
            new_name='startworkingtimeSaturday',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Fridaywork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='endworkingtimeMonday',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='endworkingtimeThursday',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='endworkingtimeTuesday',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='endworkingtimeWednesday',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='mondaywork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='saturdaywork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='startworkingtimeSunday',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='startworkingtimeThursday',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='startworkingtimeTuesday',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='startworkingtimeWednesday',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sundaywork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='thursdaywork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='tuesdaywork',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='wednesdaywork',
            field=models.BooleanField(default=True),
        ),
    ]
