# Generated by Django 2.2.6 on 2020-04-05 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_auto_20200405_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Fridaywork',
            new_name='fridaywork',
        ),
    ]
