# Generated by Django 2.2.6 on 2020-05-19 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0017_auto_20200405_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetails')),
            ],
        ),
    ]
