# Generated by Django 2.2.6 on 2020-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0018_userdetailsfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='totalregularprice',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
