# Generated by Django 2.2.6 on 2020-06-24 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import newsletter.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0019_userdetailsservicepackageprice_totalregularprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='extragift',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='headdescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='offerends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='offerstarts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='packageimage',
            field=models.ImageField(blank=True, null=True, upload_to=newsletter.models.uplodad_location_package),
        ),
        migrations.AddField(
            model_name='userdetailsservicepackageprice',
            name='slug',
            field=models.SlugField(default='miro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetailsservicepackageprice',
            name='packagepricediscount',
            field=models.IntegerField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        
    ]
