# Generated by Django 2.2.6 on 2020-06-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0020_auto_20200624_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsservicepackageprice',
            name='headdescription',
            field=models.TextField(blank=True, null=True),
        ),
         migrations.CreateModel(
            name='UserDetailsServicePackagePriceRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionremark', models.CharField(blank=True, max_length=100, null=True)),
                ('userdetailsservicepackageprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.UserDetailsServicePackagePrice')),
            ],
        ),
       
    ]
