# Generated by Django 2.2.6 on 2020-06-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0020_auto_20200624_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsservicepackageprice',
            name='headdescription',
            field=models.TextField(blank=True, null=True),
        ),
       
    ]
