

#static is here mvpland_static
# postegresql - mvpland
#username -    baal130

"""
Django settings for testzs project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
from django.conf import settings

if  not settings.DEBUG: 
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
	import os

	BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


	# Quick-start development settings - unsuitable for production
	# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

	# SECURITY WARNING: keep the secret key used in production secret!
	SECRET_KEY = '_9sfr9be0ogbt7jz!5k9euc19af0gzt_0^bp$!xgcyzcv6&ws+'

	# SECURITY WARNING: don't run with debug turned on in production!
	DEBUG = True

	ALLOWED_HOSTS = ['baal130.webfactional.com']

	EMAIL_HOST='mail.khorvatiya-online.ru'
	EMAIL_HOST_USER='tetjana@khorvatiya-online.ru'
	EMAIL_HOST_PASSWORD='a1b31734485'
	EMAIL_PORT=587
	EMAIL_USE_TLS=False
	DEFAULT_FROM_EMAIL = 'tetjana@khorvatiya-online.ru'



	# Application definition

	INSTALLED_APPS = (
	    'django.contrib.admin',
	    'django.contrib.auth',
	    'django.contrib.contenttypes',
	    'django.contrib.sites',
	    'django.contrib.sessions',
	    'django.contrib.messages',
	    'django.contrib.staticfiles',
	    #third party apps
	    'crispy_forms',
    	'registration',
    	'pagedown',
    
    	'markdown_deux',
    	'datetimewidget',
    	#my_apps
    	'comments',
    	'newsletter',
    	'dataadd',
    	'django_messages',
	)

	MIDDLEWARE_CLASSES = (
	    'django.contrib.sessions.middleware.SessionMiddleware',
	    'django.middleware.common.CommonMiddleware',
	    'django.middleware.csrf.CsrfViewMiddleware',
	    'django.contrib.auth.middleware.AuthenticationMiddleware',
	    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	    'django.contrib.messages.middleware.MessageMiddleware',
	    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	    'django.middleware.security.SecurityMiddleware',
	)

	TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.request",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.static",
    "django.core.context_processors.tz",
    "django.contrib.messages.context_processors.messages",
)

	ROOT_URLCONF = 'testzs.urls'

	TEMPLATES = [
	    {
	        'BACKEND': 'django.template.backends.django.DjangoTemplates',
	        'DIRS': [os.path.join(BASE_DIR, "templates"),os.path.join(BASE_DIR, "templates/blogs")],
	        'APP_DIRS': True,
	        'OPTIONS': {
	            'context_processors': [
	                'django.template.context_processors.debug',
	                'django.template.context_processors.request',
	                'django.contrib.auth.context_processors.auth',
	                'django.contrib.messages.context_processors.messages',
	            ],
	        },
	    },
	]

	WSGI_APPLICATION = 'testzs.wsgi.application'


	# Database
	# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

	DATABASES = {
	    'default': {
	        'ENGINE':'django.db.backends.postgresql_psycopg2',
	        'NAME': "zoran",
	        'USER': "baal130",
	        'PASSWORD':"a1b31734485",
	    }
	}


	# Internationalization
	# https://docs.djangoproject.com/en/1.8/topics/i18n/

	LANGUAGE_CODE = 'en-us'

	TIME_ZONE = 'UTC'

	USE_I18N = True

	USE_L10N = True

	USE_TZ = True


	# Static files (CSS, JavaScript, Images)
	# https://docs.djangoproject.com/en/1.8/howto/static-files/

	STATIC_URL = '/static/'


	STATIC_ROOT = '/home/baal130/webapps/zoran_static'

	#os.path.join(os.path.dirname(BASE_DIR), "Static_in_venv","static_root")# copied from staticfiles(our static) dirs u invirormnt directory(izvan roota)

	STATICFILES_DIRS = (                    #staticne filovi u projektu gdje se nalaze
	    os.path.join(BASE_DIR, "Static_in_pro","our_static"),
	    # '/var/www/static/',
	    #os.path.join(os.path.dirname(BASE_DIR), "Static_in_env"),
	) 

	MEDIA_URL= '/media/'
	MEDIA_ROOT='/home/baal130/webapps/zoran_media'
	#os.path.join(os.path.dirname(BASE_DIR), "Static_in_venv","media_root")


	#Crispy FORM TAGs SETTINGs
	CRISPY_TEMPLATE_PACK ='bootstrap3'

	#DJANGO REGISTRATION REDUX SETTINGS
	ACCOUNT_ACTIVATION_DAYS=7
	REGISTRATION_AUTO_LOGIN=True
	SITE_ID=1
	#LOGIN_REDIRECT_URL ='/profile/'
	LOGIN_REDIRECT_URL ='/'