"""
Django settings for testzs project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import asgi_redis
import dj_database_url
from decouple import Csv, config
from unipath import Path
from django.utils.translation import ugettext_lazy as _


BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
  # BASE_DIR =     os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_9sfr9be0ogbt7jz!5k9euc19af0gzt_0^bp$!xgcyzcv6&ws+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testzs.herokuapp.com','mx.zoransostaric.com','127.0.0.1','www.traveldoctor.mx','traveldoctor.mx', 'mx.traveldoctor.mx']
SERVICE_LIST = []

# EMAIL_HOST='mail.zoransostaric.com'
# EMAIL_HOST_USER='doctores@zoransostaric.com'
# EMAIL_HOST_PASSWORD='a1b31734485'
# EMAIL_PORT=587
# EMAIL_USE_TLS=False
# DEFAULT_FROM_EMAIL = 'doctores@zoransostaric.com'
# EMAIL_HOST='mail.zoransostaric.com'
# EMAIL_HOST_USER='doctores@zoransostaric.com'
# EMAIL_HOST_PASSWORD='a1b31734485'
# EMAIL_PORT=587
# EMAIL_USE_TLS=False
# DEFAULT_FROM_EMAIL = 'doctores@zoransostaric.com'

# EMAIL_HOST='smtp.gmail.com'
# EMAIL_HOST_USER='traveldoctor@traveldoctor.mx'
# EMAIL_HOST_PASSWORD='a1b31734485'
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# DEFAULT_FROM_EMAIL = 'traveldoctor@traveldoctor.mx'

EMAIL_HOST='smtp.sendgrid.net'
EMAIL_HOST_USER='apikey'
EMAIL_HOST_PASSWORD=os.environ.get("EMAIL_HOST_PASSWORD",'none')
EMAIL_PORT=587
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL = 'traveldoctor@traveldoctor.mx'



# Application definition

GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')
GEO_DEFAULT_IP='72.14.207.99'

GOOGLE_CLIENT_API=os.environ.get("GOOGLE_CLIENT_API",'none')

YELP_CLIENT_ID = os.environ.get("YELP_CLIENT_ID",'none')
YELP_CLIENT_SECRET = os.environ.get("YELP_CLIENT_SECRET",'none')

STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "sk_test_51HAz6mK450KPF3SvmxEbhWYxXlSeCyWqz3kgi84kq7K9wVfAmT6urWGbINpytrOmInGoaGMJB8iMarUbTv9KcOAy00vb5u6Zom")
STRIPE_PUB_KEY = os.environ.get("STRIPE_PUB_KEY", 'pk_test_51HAz6mK450KPF3SvgemanIaOP0CitUb0SlnZU0m1KkDbfRnLduciXwJYTuJIwZXklY6p5yi90dUVlcl2NLMH4q7C009Cxq5h0Y')

INSTALLED_APPS = (
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'robots',
    'meta',

    # 'django.contrib.gis',
    'bootstrap_datepicker_plus',
    'bootstrap3',
    'bootstrap_modal_forms',
    #third party apps
    'crispy_forms',
    'registration',
    'pagedown',
    'el_pagination',
    'django_select2', 
    'storages',
    # 'cities',
    'django_summernote',
    'markdownx',
    'markdown_deux',
    'ckeditor',
    'datetimewidget',
    # 'friendship',

    'bootcamp.core',
    'bootcamp.messenger',
    'channels',
      #my_aps_eccomerce
    'accounts',   
    'billing',
    'orders',
    'addresses',
     #my_apps
    'comments',
    'newsletter',
    'dataadd',
    # 'django_messages',
    'chat',
    'carts',
    'products',
    'analytics',
    'search',
    'widget_tweaks',
    #social apps/auth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
)

MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'whitenoise.middleware.WhiteNoiseMiddleware',




)
ROBOTS_USE_SCHEME_IN_HOST = True

# for HTTPS AND REDIRECTS TO HTTPS://www.
CORS_REPLACE_HTTPS_REFERER      = True
SECURE_PROXY_SSL_HEADER         = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT             = True
SESSION_COOKIE_SECURE           = True
CSRF_COOKIE_SECURE              = True
SECURE_HSTS_INCLUDE_SUBDOMAINS  = True
SECURE_HSTS_SECONDS             = 1000000
SECURE_FRAME_DENY               = True

ROOT_URLCONF = 'testzs.urls'

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
#     'django.template.loaders.eggs.Loader',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates"),
           os.path.join(BASE_DIR,"templates/templatesshowmore"),
           os.path.join(BASE_DIR, "templates/doctortemplate"),
           os.path.join(BASE_DIR, "templates/doctortemplate/email_templates"),
           os.path.join(BASE_DIR, "templates/ecommerce"),
           os.path.join(BASE_DIR, "templates/landing"),
            ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                
            ],


            'libraries':
            {
            'newsletter_tags': 'newsletter.templatetags.newsletter_tag',

            }
        },
    },
]

WSGI_APPLICATION = 'testzs.wsgi.application'
AUTHENTICATION_BACKENDS = (
    ('django.contrib.auth.backends.ModelBackend'),
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        
    }
}
import dj_database_url
db_from_env = dj_database_url.config()
DATABASES['default'].update(db_from_env)
#for caching (memchache heroku)

servers = os.environ.get("MEMCACHIER_SERVERS",'none')
username = os.environ.get("MEMCACHIER_USERNAME",'none')
password = os.environ.get("MEMCACHIER_PASSWORD",'none')

CACHES = {
    'default': {
        # Use django-bmemcached
        'BACKEND': 'django_bmemcached.memcached.BMemcached',

        # TIMEOUT is not the connection timeout! It's the default expiration
        # timeout that should be applied to keys! Setting it to `None`
        # disables expiration.
        'TIMEOUT': None,

        'LOCATION': servers,

        'OPTIONS': {
            'username': username,
            'password': password,
        }
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-es'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

LANGUAGES = [
    ('es', _('Espanol')),
    ('en', _('English')),
]

DATE_INPUT_FORMATS=[
    '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M:%S.%f',  # '2006-10-25 14:30:59.000200'
    '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
    '%Y-%m-%d',              # '2006-10-25'
    '%m/%d/%Y %H:%M:%S',     # '10/25/2006 14:30:59'
    '%m/%d/%Y %H:%M:%S.%f',  # '10/25/2006 14:30:59.000200'
    '%m/%d/%Y %H:%M',        # '10/25/2006 14:30'
    '%m/%d/%Y',              # '10/25/2006'
    '%m/%d/%y %H:%M:%S',     # '10/25/06 14:30:59'
    '%m/%d/%y %H:%M:%S.%f',  # '10/25/06 14:30:59.000200'
    '%m/%d/%y %H:%M',        # '10/25/06 14:30'
    '%m/%d/%y',              # '10/25/06'
]
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True
# if this is true gogle map will not work longiture is receveid like 1,5 instead 1.5 , can be resloved with localization off tag
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = '/static/'
STATICFILES_DIRS = (                    #staticne filovi u projektu gdje se nalaze kopiraju se u static root koji se koristi
    os.path.join(BASE_DIR, "Static_in_pro","our_static"),
   
) 

STATIC_ROOT = os.path.join(BASE_DIR, "live-static-files","static_root")# copied from staticfiles(our static) dirs u invirormnt directory(izvan roota)

# STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'


# MEDIA_URL= '/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, "live-static-files","media_root")


CKEDITOR_UPLOAD_PATH = "uploads/"
#Crispy FORM TAGs SETTINGs
CRISPY_TEMPLATE_PACK ='bootstrap3'
BOOTSTRAP3 = {
    'include_jquery': True,
}
#DJANGO REGISTRATION REDUX SETTINGS
# ACCOUNT_ACTIVATION_DAYS=7
# REGISTRATION_AUTO_LOGIN=True
SITE_ID=3
ROBOTS_SITEMAP_URLS = [
    'https://www.traveldoctor.mx/sitemap.xml',
]
#LOGIN_REDIRECT_URL ='/profile/'
# LOGIN_REDIRECT_URL ='/'
#Specifies the login method to use – whether the user logs in
 #by entering their username, e-mail address, 
#or either one of both. Setting this to “email” requires ACCOUNT_EMAIL_REQUIRED=True
##FOR ALLAUTH
ACCOUNT_AUTHENTICATION_METHOD ="username_email"
ACCOUNT_EMAIL_REQUIRED= True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7
ACCOUNT_EMAIL_CONFIRMATION = "mandatory"
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
LOGIN_ON_EMAIL_CONFIRMATION = True
LOGIN_REDIRECT_URL ='/'
SOCIALACCOUNT_AUTO_SIGNUP =True
SOCIALACCOUNT_EMAIL_VERIFICATION="none"
SOCIALACCOUNT_STORE_TOKENS =True

# REDIS setup
REDIS_URL = config('REDIS_URL', default=('localhost', 6379))
# # Channels configuration

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL, ],   #URL JE U env. filu
        },
        'ROUTING': 'bootcamp.routing.channel_routing',
    }
}

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v7.0',
    }
}


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#              'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
#         },
#     },
# }


AWS_ACCESS_KEY_ID = "AKIAWDFTQUMH57RFOZNM"
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY",'none')


AWS_FILE_EXPIRE = 200
AWS_PRELOAD_METADATA = True
AWS_QUERYSTRING_AUTH = False

DEFAULT_FILE_STORAGE = 'testzs.utils.MediaRootS3BotoStorage'
STATICFILES_STORAGE = 'testzs.utils.StaticRootS3BotoStorage'
AWS_STORAGE_BUCKET_NAME = 'todosdoctores1'
S3DIRECT_REGION = 'sa-east-1'
S3_URL = '//%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
MEDIA_URL = '//%s.s3.amazonaws.com/media/' % AWS_STORAGE_BUCKET_NAME
MEDIA_ROOT = MEDIA_URL
STATIC_URL = S3_URL + 'static/'
ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'

import datetime

two_months = datetime.timedelta(days=61)
date_two_months_later = datetime.date.today() + two_months
expires = date_two_months_later.strftime("%A, %d %B %Y 20:00:00 GMT")

AWS_S3_OBJECT_PARAMETERS = { 
    'Expires': expires,
    'CacheControl': 'max-age=%d' % (int(two_months.total_seconds()), ),
}


SUMMERNOTE_CONFIG = {

'disable_upload': True,


# 'attachment_upload_to': MEDIA_URL,
}


META_SITE_DOMAIN='www.traveldoctor.mx'
META_SITE_PROTOCOL='https'
META_SITE_NAME='TravelDoctor'
META_USE_SITES=True
META_USE_OG_PROPERTIES=True
META_USE_TWITTER_PROPERTIES=True
META_USE_SCHEMAORG_PROPERTIES=True
META_INCLUDE_KEYWORDS='Mexico doctors','Search nearby doctors/dentists in Mexico','consultorios medicos','Pharmacy Doctor', 'Pharmacy Online' 