# Generated by Django 2.2.6 on 2020-07-01 08:14

import dataadd.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=dataadd.models.uplodad_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('name', models.CharField(default='a', max_length=60)),
                ('surname', models.CharField(default='a', max_length=60)),
                ('adress', models.CharField(default='a', max_length=60)),
                ('city', models.CharField(default='a', max_length=60)),
                ('publish', models.DateField(default=datetime.date.today)),
                ('read_time', models.TimeField(blank=True, null=True)),
                ('name_visible', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('article', models.BooleanField(default=False)),
                ('news', models.BooleanField(default=False)),
                ('cities', models.CharField(blank=True, choices=[('', '----'), ('Bjelovarsko-bilogorska', 'BJELOVARSKO-BILOGORSKA'), ('Brodsko-posavska', 'BRODSKO-POSAVSKA'), ('Dubrovacko-neretvanska', 'DUBROVACKO-NERETVANSKA'), ('Istarska', 'ISTARSKA'), ('Karlovacka', 'KARLOVACKA')], default='null', max_length=60)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='FriendsRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerrequest', to=settings.AUTH_USER_MODEL)),
                ('usersRequests', models.ManyToManyField(related_name='senderrequests', to=settings.AUTH_USER_MODEL)),
                ('usersRequestsSent', models.ManyToManyField(related_name='senderrequestssent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
