# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:52
from __future__ import unicode_literals

import dataadd.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=dataadd.models.uplodad_location, width_field=b'width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('name', models.CharField(default=b'a', max_length=60)),
                ('surname', models.CharField(default=b'a', max_length=60)),
                ('adress', models.CharField(default=b'a', max_length=60)),
                ('city', models.CharField(default=b'a', max_length=60)),
                ('publish', models.DateField(default=datetime.date.today)),
                ('name_visible', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
