# Generated by Django 2.2.6 on 2020-07-01 08:06

import dataadd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiot',
            name='article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idiot',
            name='cities',
            field=models.CharField(blank=True, choices=[('', '----'), ('Bjelovarsko-bilogorska', 'BJELOVARSKO-BILOGORSKA'), ('Brodsko-posavska', 'BRODSKO-POSAVSKA'), ('Dubrovacko-neretvanska', 'DUBROVACKO-NERETVANSKA'), ('Istarska', 'ISTARSKA'), ('Karlovacka', 'KARLOVACKA')], default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='idiot',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idiot',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='adress',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='city',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=dataadd.models.uplodad_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='name',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='surname',
            field=models.CharField(default='a', max_length=60),
        ),
    ]
