# Generated by Django 2.2.6 on 2020-07-01 07:42

import dataadd.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataadd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiot',
            name='article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idiot',
            name='cities',
            field=models.CharField(blank=True, choices=[('', '----'), ('Bjelovarsko-bilogorska', 'BJELOVARSKO-BILOGORSKA'), ('Brodsko-posavska', 'BRODSKO-POSAVSKA'), ('Dubrovacko-neretvanska', 'DUBROVACKO-NERETVANSKA'), ('Istarska', 'ISTARSKA'), ('Karlovacka', 'KARLOVACKA')], default='null', max_length=60),
        ),
        migrations.AddField(
            model_name='idiot',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idiot',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='adress',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='city',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=dataadd.models.uplodad_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='name',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='surname',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.CreateModel(
            name='FriendsRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerrequest', to=settings.AUTH_USER_MODEL)),
                ('usersRequests', models.ManyToManyField(related_name='senderrequests', to=settings.AUTH_USER_MODEL)),
                ('usersRequestsSent', models.ManyToManyField(related_name='senderrequestssent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
