# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0002_idiot_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiot',
            name='color',
            field=models.CharField(choices=[(b'green', b'GREEN'), (b'blue', b'BLUE'), (b'red', b'RED'), (b'orange', b'ORANGE'), (b'black', b'BLACK')], default=b'green', max_length=6),
        ),
    ]
