# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-28 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0005_auto_20170416_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiot',
            name='color',
            field=models.CharField(blank=True, choices=[(b'', b'----'), (b'Zagreb', b'ZAGREB'), (b'Karlovac', b'KARLOVAC'), (b'red', b'RED'), (b'orange', b'ORANGE'), (b'black', b'BLACK')], default=b'null', max_length=6),
        ),
    ]
