# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-28 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0006_auto_20170628_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idiot',
            old_name='color',
            new_name='cities',
        ),
    ]
