# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-28 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0008_auto_20170628_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiot',
            name='cities',
            field=models.CharField(blank=True, choices=[(b'', b'----'), (b'Bjelovarsko-bilogorska', b'BJELOVARSKO-BILOGORSKA'), (b'Brodsko-posavska', b'BRODSKO-POSAVSKA'), (b'Dubrovacko-neretvanska', b'DUBROVACKO-NERETVANSKA'), (b'Istarska', b'ISTARSKA'), (b'Karlovacka', b'KARLOVACKA')], default=b'null', max_length=40),
        ),
    ]
