# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0009_auto_20170628_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiot',
            name='article',
            field=models.BooleanField(default=False),
        ),
    ]
