# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0010_idiot_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiot',
            name='news',
            field=models.BooleanField(default=False),
        ),
    ]
