# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-08 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0013_friends_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='users',
            field=models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
