# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-26 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataadd', '0014_auto_20171208_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerrequest', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='senderrequests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
