# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-26 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataadd', '0015_friendsrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsrequests',
            old_name='users',
            new_name='usersRequests',
        ),
        migrations.AddField(
            model_name='friendsrequests',
            name='usersRequestsSent',
            field=models.ManyToManyField(related_name='senderrequestssent', to=settings.AUTH_USER_MODEL),
        ),
    ]
