# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-17 21:14
from __future__ import unicode_literals

import dataadd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataadd', '0016_auto_20171226_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiot',
            name='adress',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='cities',
            field=models.CharField(blank=True, choices=[('', '----'), ('Bjelovarsko-bilogorska', 'BJELOVARSKO-BILOGORSKA'), ('Brodsko-posavska', 'BRODSKO-POSAVSKA'), ('Dubrovacko-neretvanska', 'DUBROVACKO-NERETVANSKA'), ('Istarska', 'ISTARSKA'), ('Karlovacka', 'KARLOVACKA')], default='null', max_length=40),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='city',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=dataadd.models.uplodad_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='name',
            field=models.CharField(default='a', max_length=60),
        ),
        migrations.AlterField(
            model_name='idiot',
            name='surname',
            field=models.CharField(default='a', max_length=60),
        ),
    ]
