from django.utils.translation import ugettext_lazy as _

Language_CHOICES = (
('Acholi','Acholi'),
('Afrikaans','Afrikaans'),
('Akan','Akan'),
('Albanian','Albanian'),
('Amharic','Amharic'),
('Arabic','Arabic'),
('Ashante','Ashante'),
('Asl','Asl'),
('Assyrian','Assyrian'),
('Azerbaijani','Azerbaijani'),
('Azeri','Azeri'),
('Bajuni','Bajuni'),
('Basque','Basque'),
('Behdini','Behdini'),
('Belorussian','Belorussian'),
('Bengali','Bengali'),
('Berber','Berber'),
('Bosnian','Bosnian'),
('Bravanese','Bravanese'),
('Bulgarian','Bulgarian'),
('Burmese','Burmese'),
('Cakchiquel','Cakchiquel'),
('Cambodian','Cambodian'),
('Cantonese','Cantonese'),
('Catalan','Catalan'),
('Chaldean','Chaldean'),
('Chamorro','Chamorro'),
('Chao-chow','Chao-chow'),
('Chavacano','Chavacano'),
('Chin','Chin'),
('Chuukese','Chuukese'),
('Cree','Cree'),
('Croatian','Croatian'),
('Czech','Czech'),
('Dakota','Dakota'),
('Danish','Danish'),
('Dari','Dari'),
('Dinka','Dinka'),
('Diula','Diula'),
('Dutch','Dutch'),
('Edo','Edo'),
('English','English'),
('Estonian','Estonian'),
('Ewe','Ewe'),
('Fante','Fante'),
('Farsi','Farsi'),
('Fijian Hindi','Fijian Hindi'),
('Finnish','Finnish'),
('Flemish','Flemish'),
('French','French'),
('French Canadian','French Canadian'),
('Fukienese','Fukienese'),
('Fula','Fula'),
('Fulani','Fulani'),
('Fuzhou','Fuzhou'),
('Ga','Ga'),
('Gaddang','Gaddang'),
('Gaelic','Gaelic'),
('Gaelic-irish','Gaelic-irish'),
('Gaelic-scottish','Gaelic-scottish'),
('Georgian','Georgian'),
('German','German'),
('Gorani','Gorani'),
('Greek','Greek'),
('Gujarati','Gujarati'),
('Haitian Creole','Haitian Creole'),
('Hakka','Hakka'),
('Hakka-chinese','Hakka-chinese'),
('Hausa','Hausa'),
('Hebrew','Hebrew'),
('Hindi','Hindi'),
('Hmong','Hmong'),
('Hungarian','Hungarian'),
('Ibanag','Ibanag'),
('Ibo','Ibo'),
('Icelandic','Icelandic'),
('Igbo','Igbo'),
('Ilocano','Ilocano'),
('Indonesian','Indonesian'),
('Inuktitut','Inuktitut'),
('Italian','Italian'),
('Jakartanese','Jakartanese'),
('Japanese','Japanese'),
('Javanese','Javanese'),
('Kanjobal','Kanjobal'),
('Karen','Karen'),
('Karenni','Karenni'),
('Kashmiri','Kashmiri'),
('Kazakh','Kazakh'),
('Kikuyu','Kikuyu'),
('Kinyarwanda','Kinyarwanda'),
('Kirundi','Kirundi'),
('Korean','Korean'),
('Kosovan','Kosovan'),
('Kotokoli','Kotokoli'),
('Krio','Krio'),
('Kurdish','Kurdish'),
('Kurmanji','Kurmanji'),
('Kyrgyz','Kyrgyz'),
('Lakota','Lakota'),
('Laotian','Laotian'),
('Latvian','Latvian'),
('Lingala','Lingala'),
('Lithuanian','Lithuanian'),
('Luganda','Luganda'),
('Luo','Luo'),
('Maay','Maay'),
('Macedonian','Macedonian'),
('Malay','Malay'),
('Malayalam','Malayalam'),
('Maltese','Maltese'),
('Mandarin','Mandarin'),
('Mandingo','Mandingo'),
('Mandinka','Mandinka'),
('Marathi','Marathi'),
('Marshallese','Marshallese'),
('Mien','Mien'),
('Mina','Mina'),
('Mirpuri','Mirpuri'),
('Mixteco','Mixteco'),
('Moldavan','Moldavan'),
('Mongolian','Mongolian'),
('Montenegrin','Montenegrin'),
('Navajo','Navajo'),
('Neapolitan','Neapolitan'),
('Nepali','Nepali'),
('Nigerian Pidgin','Nigerian Pidgin'),
('Norwegian','Norwegian'),
('Oromo','Oromo'),
('Pahari','Pahari'),
('Papago','Papago'),
('Papiamento','Papiamento'),
('Pashto','Pashto'),
('Patois','Patois'),
('Pidgin English','Pidgin English'),
('Polish','Polish'),
('Portug.creole','Portug.creole'),
('Portuguese','Portuguese'),
('Pothwari','Pothwari'),
('Pulaar','Pulaar'),
('Punjabi','Punjabi'),
('Putian','Putian'),
('Quichua','Quichua'),
('Romanian','Romanian'),
('Russian','Russian'),
('Samoan','Samoan'),
('Serbian','Serbian'),
('Shanghainese','Shanghainese'),
('Shona','Shona'),
('Sichuan','Sichuan'),
('Sicilian','Sicilian'),
('Sinhalese','Sinhalese'),
('Slovak','Slovak'),
('Somali','Somali'),
('Sorani','Sorani'),
('Spanish','Spanish'),
('Sudanese Arabic','Sudanese Arabic'),
('Sundanese','Sundanese'),
('Susu','Susu'),
('Swahili','Swahili'),
('Swedish','Swedish'),
('Sylhetti','Sylhetti'),
('Tagalog','Tagalog'),
('Taiwanese','Taiwanese'),
('Tajik','Tajik'),
('Tamil','Tamil'),
('Telugu','Telugu'),
('Thai','Thai'),
('Tibetan','Tibetan'),
('Tigre','Tigre'),
('Tigrinya','Tigrinya'),
('Toishanese','Toishanese'),
('Tongan','Tongan'),
('Toucouleur','Toucouleur'),
('Trique','Trique'),
('Tshiluba','Tshiluba'),
('Turkish','Turkish'),
('Twi','Twi'),
('Ukrainian','Ukrainian'),
('Urdu','Urdu'),
('Uyghur','Uyghur'),
('Uzbek','Uzbek'),
('Vietnamese','Vietnamese'),
('Visayan','Visayan'),
('Welsh','Welsh'),
('Wolof','Wolof'),
('Yiddish','Yiddish'),
('Yoruba','Yoruba'),
('Yupik','Yupik'),

)

Favicon_CHOICES = (
	('flaticon','flaticon-group'),
	('flaticon-medical-30','flaticon-medical-30'),
	('flaticon-medical-28','flaticon-medical-28'),
	('flaticon-medical-27','flaticon-medical-27'),
	('flaticon-technology-1','flaticon-technology-1'),
	('flaticon-silhouette','flaticon-silhouette'),
	('flaticon-cross','flaticon-cross'),
	('flaticon-people-15','flaticon-people-15'),
	('flaticon-medical-24','flaticon-medical-24'),
	('flaticon-sign-1','flaticon-sign-1'),
	('flaticon-medical-23','flaticon-medical-23'),
	('flaticon-circle','flaticon-circle'),
	('flaticon-medical-20','flaticon-medical-20'),
	('flaticon-medical-18','flaticon-medical-18'),
	('flaticon-people-11','flaticon-people-11'),
	('flaticon-people-8','flaticon-people-8'),
	('flaticon-medical-12','flaticon-medical-12'),
	('flaticon-medical-11','flaticon-medical-11'),
	('flaticon-medical-10','flaticon-medical-10'),
	('flaticon-black','flaticon-black'),
	('flaticon-medical-7','flaticon-medical-7'),
	('flaticon-caduceus-medical-symbol','flaticon-caduceus-medical-symbol'),
	('flaticon-heart-checkup','flaticon-heart-checkup'),
	('flaticon-woman-with-hat-of-red-cross','flaticon-woman-with-hat-of-red-cross'),
	('flaticon-blood-pressure-control-tool','flaticon-blood-pressure-control-tool'),
	('flaticon-blood-analysis','flaticon-blood-analysis'),
	('flaticon-lab-flask','flaticon-lab-flask'),
	('flaticon-medical-5','flaticon-medical-5'),
	('flaticon-knee','flaticon-knee'),
	('flaticon-medical-2','flaticon-medical-2'),
	('flaticon-medical-1','flaticon-medical-1'),
	('flaticon-medical','flaticon-medical'),
	('flaticon-disabled','flaticon-disabled'),
	('flaticon-disability','flaticon-disability'),
	('flaticon-pregnancy','flaticon-pregnancy'),
	('flaticon-x-ray-of-bones','flaticon-x-ray-of-bones'),
	('flaticon-baby-with-diaper','flaticon-baby-with-diaper'),
	('flaticon-mother-with-baby-in-arms','flaticon-mother-with-baby-in-arms'),
	('flaticon-lungs-with-bronchi','flaticon-lungs-with-bronchi'),
	('flaticon-urinary-system','flaticon-urinary-system'),
	('flaticon-kidney','flaticon-kidney'),
	('flaticon-brain-cenit-view','flaticon-brain-cenit-view'),
	('flaticon-brain-and-head','flaticon-brain-and-head'),
	('flaticon-pills','flaticon-pills'),
	('flaticon-tooth-1','flaticon-tooth-1'),
	('flaticon-ambulance','flaticon-ambulance'),
	('flaticon-heartbeat','flaticon-heartbeat'),
	('flaticon-health-care','flaticon-health-care'),
	('flaticon-sound-frequency','flaticon-sound-frequency'),
	('flaticon-visible-opened-eye-interface-option','flaticon-visible-opened-eye-interface-option'),
	('flaticon-eye-on-magnifying-glass','flaticon-eye-on-magnifying-glass'),
	('flaticon-eye-drop','flaticon-eye-drop'),
	('flaticon-gum','flaticon-gum'),
	('flaticon-molar-crown','flaticon-molar-crown'),
	('flaticon-braces','flaticon-braces'),
	('flaticon-implants','flaticon-implants'),	
)


STATE_CHOICES = (
	('',_('Select_state')),
	('Aguascalientes', 'AGUASCALIENTES'),
	('Baja California','BAJA CALIFORNIA'),
	('Baja California Sur', 'BAJA CALIFORNIA SUR'),
	('Campeche', 'CAMPECHE'),
	('Chiapas', 'CHIAPAS'),
	('Mexico City', 'MEXICO CITY'),
	('Chihuahua', 'CHIHUAHUA'),
	('Coahuila', 'COAHUILA'),
	('Colima','COLIMA'),
	('Durango', 'DURANGO'),
	('Guanajuato', 'GUANAJUATO'),
	('Guerrero', 'GUERRERO'),
	('Hidalgo', 'HIDALGO'),
	('Jalisco', 'JALISCO'),
	('Mexico', 'MEXICO'),
	('Michoacan','MICHOACAN'),
	('Morelos', 'MORELOS'),
	('Nayarit', 'NAYARIT'),
	('Nuevo Leon', 'NUEVO LEON'),
	('Oaxaca', 'OAXACA'),
	('Puebla', 'PUEBLA'),
	('Queretaro', 'QUERETARO'),
	('Quintana Roo','QUINTANA ROO'),
	('San Luis Potosi', 'SAN LUIS POTOSI'),
	('Sinaloa', 'SINALOA'),
	('Sonora', 'SONORA'),
	('Tabasco', 'TABASCO'),
	('Tamaulipas', 'TAMAULIPAS'),
	('Tlaxcala', 'TLAXCALA'),
	('Veracruz','VERACRUZ'),
	('Yucatan', 'YUCATAN'),
	('Zacatecas', 'ZACATECAS'),	
)

CITY_CHOICES = (
('', _('Select_city')),
('Acapulco de Juárez','Acapulco de Juarez'),
('Acatlán de Osorio','Acatlan de Osorio'),
('Agua Prieta','Agua Prieta'),
('Aguascalientes','Aguascalientes'),
('Ahumada','Ahumada'),
('Aldama','Aldama'),
('Allende','Allende'),
('Altata','Altata'),
('Apatzingan de la Constitucion','Apatzingan de la Constitucion'),
('Ascensión','Ascension'),
('Atoyac de Álvarez','Atoyac de Alvarez'),
('Autlán de Navarro','Autlan de Navarro'),
('Ayutla de los Libres','Ayutla de los Libres'),
('Balancán','Balancan'),
('Cabo San Lucas','Cabo San Lucas'),
('Camargo','Camargo'),
('Campeche','Campeche'),
('Cananea','Cananea'),
('Canatlán','Canatlan'),
('Cancún','Cancun'),
('Cárdenas','Cardenas'),
('Celaya','Celaya'),
('Champotón','Champoton'),
('Chetumal','Chetumal'),
('Chihuahua','Chihuahua'),
('Chilpancingo','Chilpancingo'),
('Ciudad Altamirano','Ciudad Altamirano'),
('Ciudad Constitución','Ciudad Constitucion'),
('Ciudad de Atlixco','Ciudad de Atlixco'),
('Ciudad de Huajuapam de León','Ciudad de Huajuapam de Leon'),
('Ciudad del Carmen','Ciudad del Carmen'),
('Ciudad Guzmán','Ciudad Guzman'),
('Ciudad Hidalgo','Ciudad Hidalgo'),
('Ciudad Lázaro Cárdenas','Ciudad Lazaro Cardenas'),
('Ciudad Madero','Ciudad Madero'),
('Ciudad Mante','Ciudad Mante'),
('Ciudad Nezahualcóyotl','Ciudad Nezahualcoyotl'),
('Ciudad Obregón','Ciudad Obregon'),
('Ciudad Sabinas Hidalgo','Ciudad Sabinas Hidalgo'),
('Ciudad Tula','Ciudad Tula'),
('Ciudad Valles','Ciudad Valles'),
('Ciudad Victoria','Ciudad Victoria'),
('Coalcomán de Vázquez Pallares','Coalcoman de Vazquez Pallares'),
('Coatzacoalcos','Coatzacoalcos'),
('Colima','Colima'),
('Compostela','Compostela'),
('Córdoba','Cordoba'),
('Cozumel','Cozumel'),
('Cuauhtémoc','Cuauhtemoc'),
('Cuencamé de Ceniceros','Cuencame de Ceniceros'),
('Cuernavaca','Cuernavaca'),
('Culiacán','Culiacan'),
('Durango','Durango'),
('El Dorado','El Dorado'),
('El Fuerte','El Fuerte'),
('Ensenada','Ensenada'),
('Escuinapa','Escuinapa'),
('Escuintla','Escuintla'),
('Esperanza','Esperanza'),
('Felipe Carrillo Puerto','Felipe Carrillo Puerto'),
('Fresnillo','Fresnillo'),
('Frontera','Frontera'),
('Gómez Palacio','Gomez Palacio'),
('Guadalajara','Guadalajara'),
('Guamúchil','Guamuchil'),
('Guanajuato','Guanajuato'),
('Guasave','Guasave'),
('Guerrero Negro','Guerrero Negro'),
('Halachó','Halacho'),
('Hermosillo','Hermosillo'),
('Heroica Caborca','Heroica Caborca'),
('Heroica Ciudad de Tlaxiaco','Heroica Ciudad de Tlaxiaco'),
('Heroica Guaymas','Heroica Guaymas'),
('Heroica Matamoros','Heroica Matamoros'),
('Heroica Nogales','Heroica Nogales'),
('Huatabampo','Huatabampo'),
('Iguala de la Independencia','Iguala de la Independencia'),
('Irapuato','Irapuato'),
('Isla Mujeres','Isla Mujeres'),
('Izamal','Izamal'),
('Jáltipan de Morelos','Jaltipan de Morelos'),
('Juan Aldama','Juan Aldama'),
('Juárez','Juarez'),
('Juchitán de Zaragoza','Juchitan de Zaragoza'),
('La Barca','La Barca'),
('La Cruz','La Cruz'),
('La Paz','La Paz'),
('Lagos de Moreno','Lagos de Moreno'),
('Las Delicias','Las Delicias'),
('León de los Aldama','Leon de los Aldama'),
('Linares','Linares'),
('Loreto','Loreto'),
('Los Mochis','Los Mochis'),
('Magdalena de Kino','Magdalena de Kino'),
('Manzanillo','Manzanillo'),
('Matehuala','Matehuala'),
('Mazatán','Mazatan'),
('Mazatlán','Mazatlan'),
('Mérida','Merida'),
('Mexicali','Mexicali'),
('Mexico City','Mexico City'),
('Miahuatlán de Porfirio Díaz','Miahuatlan de Porfirio Diaz'),
('Minatitlán','Minatitlan'),
('Monclova','Monclova'),
('Montemorelos','Montemorelos'),
('Monterrey','Monterrey'),
('Morelia','Morelia'),
('Motul','Motul'),
('Nacozari Viejo','Nacozari Viejo'),
('Nautla','Nautla'),
('Navojoa','Navojoa'),
('Nueva Rosita','Nueva Rosita'),
('Nuevo Casas Grandes','Nuevo Casas Grandes'),
('Nuevo Laredo','Nuevo Laredo'),
('Oaxaca','Oaxaca'),
('Ojinaga','Ojinaga'),
('Ometepec','Ometepec'),
('Orizaba','Orizaba'),
('Pachuca','Pachuca'),
('Pánuco','Panuco'),
('Paraíso','Paraiso'),
('Parral','Parral'),
('Parras de la Fuente','Parras de la Fuente'),
('Petatlán','Petatlan'),
('Peto','Peto'),
('Piedras Negras','Piedras Negras'),
('Pijijiapan','Pijijiapan'),
('Poza Rica de Hidalgo','Poza Rica de Hidalgo'),
('Progreso','Progreso'),
('Puebla','Puebla'),
('Puerto Escondido','Puerto Escondido'),
('Puerto Vallarta','Puerto Vallarta'),
('Punta Prieta','Punta Prieta'),
('Querétaro','Queretaro'),
('Reynosa','Reynosa'),
('Rioverde','Rioverde'),
('Salamanca','Salamanca'),
('Salina Cruz','Salina Cruz'),
('Saltillo','Saltillo'),
('San Cristóbal','San Cristobal'),
('San Felipe','San Felipe'),
('San Fernando','San Fernando'),
('San Juan del Río','San Juan del Rio'),
('San Luis Potosí','San Luis Potosi'),
('San Miguel de Papasquiaro','San Miguel de Papasquiaro'),
('San Pablo Villa de Mitla','San Pablo Villa de Mitla'),
('San Pedro','San Pedro'),
('San Pedro Pochutla','San Pedro Pochutla'),
('San Quintín','San Quintin'),
('Santa Bárbara','Santa Barbara'),
('Santa Rosalía','Santa Rosalia'),
('Santiago Ixcuintla','Santiago Ixcuintla'),
('Santiago Tuxtla','Santiago Tuxtla'),
('Santo Domingo Tehuantepec','Santo Domingo Tehuantepec'),
('Tamazunchale','Tamazunchale'),
('Tampico','Tampico'),
('Tamuín','Tamuin'),
('Tapachula','Tapachula'),
('Taxco de Alarcón','Taxco de Alarcon'),
('Tecax','Tecax'),
('Tecomán','Tecoman'),
('Técpan de Galeana','Tecpan de Galeana'),
('Tecuala','Tecuala'),
('Tehuacán','Tehuacan'),
('Tenosique','Tenosique'),
('Tepic','Tepic'),
('Teziutlan','Teziutlan'),
('Ticul','Ticul'),
('Tijuana','Tijuana'),
('Tizimín','Tizimin'),
('Tlaxcala','Tlaxcala'),
('Toluca','Toluca'),
('Torreón','Torreon'),
('Túxpam de Rodríguez Cano','Tuxpam de Rodriguez Cano'),
('Tuxpan','Tuxpan'),
('Tuxtla','Tuxtla'),
('Uruapan','Uruapan'),
('Valladolid','Valladolid'),
('Valparaíso','Valparaiso'),
('Veracruz','Veracruz'),
('Vicente Guerrero','Vicente Guerrero'),
('Villa Unión','Villa Union'),
('Villahermosa','Villahermosa'),
('Villanueva','Villanueva'),
('Xalapa','Xalapa'),
('Zacatecas','Zacatecas'),
('Zamora','Zamora'),
('Zumpango','Zumpango'),

)
Specialty_CHOICES = (
(_(''),_('Choose_Speciality')),

(_('Alergólogo'),_('Alergólogo')),
(_('Anatomopatólogo'),_('Anatomopatólogo')),
(_('Anestesiólogo'),_('Anestesiólogo')),
(_('Angiólogo '),_('Angiólogo ')),
(_('Audiólogo '),_('Audiólogo ')),
(_('Cardiólogo'),_('Cardiólogo')),
(_('Cardiólogo pediátrico'),_('Cardiólogo pediátrico')),
(_('Cirujano cardiocacular y torácico '),_('Cirujano cardiocacular y torácico ')),
(_('Cirujano de la mano'),_('Cirujano de la mano')),
(_('Cirujano estético y cosmético'),_('Cirujano estético y cosmético')),
(_('Cirujano general'),_('Cirujano general')),
(_('Cirujano maxilofacial'),_('Cirujano maxilofacial')),
(_('Cirujano oncólogo'),_('Cirujano oncólogo')),
(_('Cirujano pediátrico'),_('Cirujano pediátrico')),
(_('Cirujano plástico'),_('Cirujano plástico')),
(_('Dermatólogo'),_('Dermatólogo')),
(_('Dermatólogo pediátrico'),_('Dermatólogo pediátrico')),
(_('Diabetólogo'),_('Diabetólogo')),
(_('Endocrinólogo'),_('Endocrinólogo')),
(_('Endocrinólogo pediátrico'),_('Endocrinólogo pediátrico')),
(_('Endoscopista'),_('Endoscopista')),
(_('Enfermero'),_('Enfermero')),
(_('Fisioterapeuta'),_('Fisioterapeuta')),
(_('Gastroenterólogo'),_('Gastroenterólogo')),
(_('Gastroenterólogo pediátrico'),_('Gastroenterólogo pediátrico')),
(_('Genetista'),_('Genetista')),
(_('Geriatra'),_('Geriatra')),
(_('Ginecólogo oncológico'),_('Ginecólogo oncológico')),
(_('Ginecólogo'),_('Ginecólogo')),
(_('Hematólogo'),_('Hematólogo')),
(_('Hematólogo pediatra'),_('Hematólogo pediatra')),
(_('Homeópata'),_('Homeópata')),
(_('Infectólogo'),_('Infectólogo')),
(_('Infectólogo pediatra'),_('Infectólogo pediatra')),
(_('Inmunólogo'),_('Inmunólogo')),
(_('Analista clínico'),_('Analista clínico')),
(_('Logopeda'),_('Logopeda')),
(_('Terapeuta complementario'),_('Terapeuta complementario')),
(_('Especialista en Medicina Crítica y Terapia Intensiva'),_('Especialista en Medicina Crítica y Terapia Intensiva')),
(_('Especialista en Medicina del Deporte'),_('Especialista en Medicina del Deporte')),
(_('Especialista en Medicina del Trabajo'),_('Especialista en Medicina del Trabajo')),
(_('Médico estético'),_('Médico estético')),
(_('Médico de familia'),_('Médico de familia')),
(_('Médico general'),_('Médico general')),
(_('Especialista en Medicina Integrada'),_('Especialista en Medicina Integrada')),
(_('Internista'),_('Internista')),
(_('Especialista en Medicina Nucle'),_('Especialista en Medicina Nucle')),
(_('Especialista en Medicina Preventiva Naturista'),_('Especialista en Medicina Preventiva Naturista')),
(_('Nefrólogo'),_('Nefrólogo')),
(_('Nefrólogo infantil'),_('Nefrólogo infantil')),
(_('Neonatólogo'),_('Neonatólogo')),
(_('Neumólogo'),_('Neumólogo')),
(_('Neumólogo pediatra'),_('Neumólogo pediatra')),
(_('Neurocirujano'),_('Neurocirujano')),
(_('Neurofisiólogo'),_('Neurofisiólogo')),
(_('Neurólogo'),_('Neurólogo')),
(_('Neurólogo infantil'),_('Neurólogo infantil')),
(_('Nutricionista'),_('Nutricionista')),
(_('Nutriólogo clínico'),_('Nutriólogo clínico')),
(_('Especialista en Obesidad y Delgadez'),_('Especialista en Obesidad y Delgadez')),
(_('Dentista - Odontólogo'),_('Dentista - Odontólogo')),
(_('Oftalmólogo'),_('Oftalmólogo')),
(_('Oftalmólogo pediátrico'),_('Oftalmólogo pediátrico')),
(_('Oncólogo'),_('Oncólogo')),
(_('Oncólogo pediátrico'),_('Oncólogo pediátrico')),
(_('Optometrista'),_('Optometrista')),
(_('Ortopedista'),_('Ortopedista')),
(_('Ortopedista infantil'),_('Ortopedista infantil')),
(_('Otorrinolaringólogo'),_('Otorrinolaringólogo')),
(_('Patólogo'),_('Patólogo')),
(_('Pediatra'),_('Pediatra')),
(_('Podiatra'),_('Podiatra')),
(_('Podólogo'),_('Podólogo')),
(_('Proctólogo'),_('Proctólogo')),
(_('Psicoanalista'),_('Psicoanalista')),
(_('Psicólogo'),_('Psicólogo')),
(_('Psicopedagogo'),_('Psicopedagogo')),
(_('Psiquiatra'),_('Psiquiatra')),
(_('Psiquiatra infantil'),_('Psiquiatra infantil')),
(_('Quiropráctico'),_('Quiropráctico')),
(_('Radiólogo'),_('Radiólogo')),
(_('Radioterapeuta'),_('Radioterapeuta')),
(_('Especialista en Rehabilitación y Medicina Física'),_('Especialista en Rehabilitación y Medicina Física')),
(_('Especialista en Retina Médica y Quirúrgica'),_('Especialista en Retina Médica y Quirúrgica')),
(_('Reumatólogo'),_('Reumatólogo')),
(_('Sexólogo'),_('Sexólogo')),
(_('Algólogo'),_('Algólogo')),
(_('Terapeuta ocupacional'),_('Terapeuta ocupacional')),
(_('Traumatólogo'),_('Traumatólogo')),
(_('Urgenciólogo'),_('Urgenciólogo')),
(_('Urólogo'),_('Urólogo')),
(_('Reumatólogo pediátrico'),_('Reumatólogo pediátrico')),

)

categoryYelp={ 'Alergólogo': 'allergist',
   'Anatomopatólogo': 'Anatomopatólogo',	
   'Anestesiólogo':'doctor', 
    'Audiólogo': 'audiologist',
    'Angiólogo': 'doctor',
    'Cardiólogo':'cardiology',
	'Cardiólogo pediátrico':'cardiology',
    'Cirujano cardiocacular y torácico':'surgeons',
    'Cirujano de la mano':'surgeons',
    'Cirujano general':'surgeons',
    'Cirujano maxilofacial':'plasticsurgeons',
    'Cirujano oncólogo':'oncologist',
    'Cirujano pediátrico':'surgeons',
    'Infectólogo':'infectiousdisease',
    'Cirujano estético y cosmético':'cosmeticsurgeons',
    'Cirujano plástico':'plasticsurgeons',
    'Dermatólogo':'dermatology',
    'Dermatólogo pediátrico':'dermatology',
    'Diabetólogo':'physicians',
    'Endocrinólogo':'endocrinologists',	
     'Endocrinólogo pediátrico':'endocrinologists',
     'Endoscopista':'doctor',
    'Enfermero':'infectiousdisease',
    'Fisioterapeuta':'infectiousdisease',
    'Gastroenterólogo':'gastroenterologist',
   'Gastroenterólogo pediátrico':'gastroenterologist',
   'Genetista':'geneticists', 
   'Geriatra':'doctor',
   'Ginecólogo oncológico':'oncologist',
   'Ginecólogo':'obgyn',
   'Hematólogo':'hepatologists',
     'Hematólogo pediatra':'hepatologists',
'Homeópata':'hepatologists',
'Infectólogo':'infectiousdisease',
'Infectólogo pediatra':'infectiousdisease',
'Inmunólogo':'immunodermatologists',
'Analista clínico':'doctor',
'Logopeda':'doctor',
'Terapeuta complementario':'doctor',
'Especialista en Medicina Crítica y Terapia Intensiva':'doctor',
'Especialista en Medicina del Deporte':'doctor',
'Especialista en Medicina del Trabajo':'doctor',
'Médico estético':'cosmeticsurgeons',
'Médico de familia':'familydr',
'Médico general':'familydr',
'Especialista en Medicina Integrada':'doctor',
'Internista':'internalmed',
'Especialista en Medicina Nucle':'radiologists',
'Especialista en Medicina Preventiva Naturista':'preventivemedicine',
'Nefrólogo':'nephrologists',
'Nefrólogo infantil':'nephrologists',
'Neonatólogo':'Neonatologist',
'Neumólogo':'Neumologist',
'Neumólogo pediatra':'Neumologist',
'Neurocirujano':'neurologist',
'Neurólogo':'neurologist',
'Neurólogo infantil':'neurologist',
'Nutricionista':'nutritionists',
'Nutriólogo clínico':'nutritionists',
'Especialista en Obesidad y Delgadez':'nutritionists',
'Dentista - Odontólogo':'dentists',
'Oftalmólogo':'Ophthalmologist',
'Oftalmólogo pediátrico':'Ophthalmologist',
'Oncólogo':'oncologist',
'Oncólogo pediátrico':'oncologist',
'Optometrista':'Optometrist',
'Ortopedista':'orthopedists',
'Ortopedista infantil':'orthopedists',
'Otorrinolaringólogo':'earnosethroat',
'Patólogo':'pathologists',
'Pediatra':'pediatricians',
'Podiatra':'podiatrists',
'Podólogo':'Chiropodist',
'Proctólogo':'proctologist',
'Psicoanalista':'psychoanalysts',
'Psicólogo':'psychologists',
'Psicopedagogo':'c_and_mh',
'Psiquiatra':'psychotherapists',
'Quiropráctico':'chiropractors',
'Radiólogo':'radiologists',
'Radioterapeuta':'Radiotherapist',
'Especialista en Rehabilitación y Medicina Física':'rehabilitation_center',
'Especialista en Retina Médica y Quirúrgica':'spinesurgeons',
'Reumatólogo':'rhematologists',
'Sexólogo':'sextherapists',
'Algólogo':'doctor',
'Terapeuta ocupacional':'c_and_mh',
'Traumatólogo':'Traumatologist',
'Radioterapeuta':'Radiotherapist',
'Urgenciólogo':'emergencymedicine',
'Urólogo':'urologists',
'Reumatólogo pediátrico':'rhematologists',
  
 }



EXTRA_CHOICES = (
	('',_('More Filter')),
	('Nearby_search', 'Nearby_search'),
	('Pet','Pet'),

)



























































































