# Generated by Django 2.2.6 on 2020-10-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201005_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='productremark',
            name='descriptionremark_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productremark',
            name='descriptionremark_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
