# Generated by Django 2.2.6 on 2020-10-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201005_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_email',
            field=models.EmailField(default='baal130@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
